# on declare la version de Docker-Compose que l'on souhaite utiliser
version: "3.8"

# on declare les services qui composeront la stack
services:

  #image mysql
  db:
    image: mysql:8.0
    container_name: poseidon_mysql_db
    volumes:
      # permet de specifier l'emplacement des donnees
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: demo
      #MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: rootroot
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-prootroot" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # image poseidon
  poseidon:
    build: .
    image: poseidon-image
    container_name: poseidon
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8087:8087"
    restart: always
    environment:
      MYSQL_HOST: db # the hostname for the running MySQL server
      MYSQL_USER: root # the username to use for the connection
      MYSQL_PASSWORD: rootroot # the password to use for the connection
      MYSQL_DB: demo # the database to use once connected
    tty: true

volumes:
  db_data: { }